### ISSUE TITLE
Can't compile due to missing hsl file

### ISSUE THREAD

**Issue by threeway** [rafael-santiago/pig#8]
Hi, I just started looking into pig because it seems interesting.  

However, it seems to require a file that I'm not sure where it comes from.

in pig/src/Forgefile.hsl, there's this line

include ~/toolsets/common/utils/lang/c/dependency_scanner.hsl

This doesn't seem to be part of hefesto at all?

The steps I followed was to download hefesto and compile it, but I'm running it from the directory I built it, rather than install it.

```
builder:~/sandbox/pig/pig/src $ ../../hefesto/bin/hefesto
hefesto WARNING: unable to resolve file name "~/toolsets/common/utils/lang/c/dependency_scanner.hsl"
hefesto WARNING: unable to resolve file name "~/toolsets/common/utils/lang/c/dependency_scanner.hsl"
```

**Comment by rafael-santiago** [comment]
Hi,

You should install it, otherwise you need to handle all environment variable stuff by your own. There is a hard way: if you call ``hefesto`` passing ``--user-includes-home`` pointing to the ``toolsets`` directory where you have built ``hefesto``, it should work but is kind of tricky and probably you will find problems to run the ``tests``. The basic idea is:

```
_hefesto --user-includes-home=/your-hefesto-local-built/helios/src/include
```
you also should add this option to the pig's ``src/.ivk`` file.

Now assuming that you have installed it as ``root`` and the problem remains...

Try to check if this file ("dependency_scanner.hsl") is really into your ``HEFESTO_INCLUDES_HOME``.

If you are not so sure about your "includes home" path, try something like:

```
_ echo $HEFESTO_INCLUDES_HOME
```

or let's generalize it:

```
_ ls $HEFESTO_INCLUDES_HOME/toolsets/common/utils/lang/c/dependency_scanner.hsl
```
Now...

- If the script file is on your filesystem, try to do a new login.

- If the file does not exist, let's install it. You should clone another repo of mine called ``helios`` and install the missing file with it.

```
_ git clone https://github.com/rafael-santiago/helios helios
_ cd helios
_ hefesto --install=c-dep-scanner
```

After doing it the related script should be installed. You can delete your helios copy, there is no problem with it.

Let me know if you solved the problem and how you solved it. Your feedback can help me to tune the things up, if something wrong is really occurring.

Thank you!

**Comment by rafael-santiago** [comment]
Destination unreachable.
